# Generated by Django 5.2.8 on 2026-01-10 12:23

import core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_background_gradient',
            field=models.CharField(blank=True, help_text='CSS gradient string for profile background', max_length=200, null=True),
        ),
    ]
