# Generated by Django 5.2.8 on 2026-01-11 00:44

import core.models.course
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_avatar_user_profile_background_gradient'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Course cover image', max_length=500, null=True, upload_to=core.models.course.course_image_upload_path),
        ),
    ]
