# Generated by Django 5.2.8 on 2026-01-18 01:29

import core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_auth_provider_user_avatar_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_background_gradient',
            field=models.CharField(blank=True, help_text='CSS gradient string for profile background', max_length=500, null=True),
        ),
    ]
