# Generated by Django 5.2.8 on 2026-01-18 00:00
#
# NOTE:
# Some databases already have the `avatar` column (created manually or via an older
# migration history). This migration keeps Django state consistent without trying
# to re-add a duplicate column at the DB level.

import core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_user_github_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="avatar",
                    field=models.ImageField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=core.models.user.user_avatar_upload_path,
                    ),
                )
            ],
        ),
    ]

