# Generated by Django 5.2.8 on 2026-01-24 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='topic',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit for timed tests in seconds (minimum 30, maximum 1800)', null=True, validators=[django.core.validators.MinValueValidator(30)]),
        ),
    ]
